site_name: Bliss OS Documentation
repo_name: BlissOS/Documentation
repo_url: https://github.com/BlissRoms-x86/Documentation
theme:
  name: material
  favicon: assets/images/favicon.png
  custom_dir: assets_main
  palette:
    - scheme: blisslight
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Google Sans Flex
    code: Google Sans Code
  icon:
    logo: blissos
    annotation: material/plus-circle
  features:
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.annotate
extra_css:
  - assets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra:
  social:
    - icon: octicons/globe-16
      link: https://blissos.org/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/blissos_org
    - icon: fontawesome/brands/telegram
      link: https://t.me/blissx86
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/F9n5gbdNy2
copyright: Copyright © 2013 - 2026 BlissLabs
nav:
  - Main Page: README.md
  - Installation guide:
      - installation/README.md
      - Automatic with Installers:
          - Bootable Installer: installation/auto/bootable-installer.md
      - Manual Setup:
          - The basics: installation/manual/the-basics.md
          - Setup Linux's GRUB2: installation/manual/setup-linux-grub2.md
          - Setup rEFInd: installation/manual/setup-refind.md
      - Install on a Virtual Machine: installation/vm.md
  - Configuration:
      - configuration/README.md
      - Audio: configuration/audio.md
      - Display: configuration/display.md
      - Graphics:
        - configuration/graphics/README.md
        - DriConf: configuration/graphics/driconf.md
        - Intel GPUs: configuration/graphics/intel.md
        - AMD GPUs: configuration/graphics/amd-radeon.md
        - Nvidia GPUs: configuration/graphics/nvidia.md
        - VirGL: configuration/graphics/virtio.md
        - VMWare SVGA: configuration/graphics/vmware.md
      - Media codecs: configuration/media-codecs.md
      - Sensors: configuration/sensors.md
      - Touchscreen:
        - Calibrate and configure iptsd: configuration/touchscreens/calibrate-configure-iptsd.md
        - Calibrate and configure silead touchscreens: configuration/touchscreens/calibrate-configure-silead.md
      - Grant superuser permission or debug shell: configuration/grantsu.md
      - Preparing a Virtual Machine: configuration/vm-setup.md
      - Pseudo fstab: configuration/pseudo-filesystem-table.md
      - Setup kernel's cmdline parameters: configuration/kernel-parameters.md
      - Recovery Mode: configuration/recovery.md
      - Making Panda/Mantis keymapper work: configuration/arm-keymapper-hack.md
  - Knowledgebase:
      - knowledgebase/README.md
      - Hardware Requirements: knowledgebase/hardware-requirement.md
      - Different BlissOS variants:
          - knowledgebase/other-bliss-variant/README.md
          - BlissOS Go: knowledgebase/other-bliss-variant/go-builds.md
          - BlissOS for Surface devices: knowledgebase/other-bliss-variant/surface-builds.md
          - BlissOS Zenith: knowledgebase/other-bliss-variant/zenith-builds.md
      - Difference with BlissRoms: knowledgebase/difference-with-blissroms.md
      - Graphics options explanation: knowledgebase/graphics-explain.md
      - Pseudo filesystem table: knowledgebase/pseudo-filesystem-table.md
      - Userdata options: knowledgebase/userdata-options.md
      - BlissOS' kernel parameters cheat sheets: knowledgebase/kernel-parameters-cheat-sheet.md
      - External resources: knowledgebase/external-resources.md
      - Compatibility List: knowledgebase/compatibility-list.md
  - Development:
      - development/README.md
      - Maintaining Proper Authorship: development/maintaining-proper-authorship.md
      - Obtain the Source Code: development/obatain-source-and-build.md
      - Porting Linux Drivers: development/porting-linux-drivers.md
      - Contribute to the Documentation: development/contribute-to-the-documentation.md
  - Feedback:
      - feedback/README.md
      - Github Issues: feedback/github-issue.md
      - Messaging Platforms: feedback/messaging.md
      - XDA Threads: feedback/xda.md
  - Frequently Asked Questions (FAQs): faq.md
  - Code of Conduct: CODE_OF_CONDUCT.md
plugins:
  - glightbox
  - search
  - table-reader
